#!/usr/bin/env python3
"""
Server-side render the publication list into index.html at build time.

The homepage renders publications client-side from data/pubs.json (see the
renderPubs() script in index.html), which is great for interactivity but
leaves the initial HTML's <ol id="pub-list"> empty — so no-JS crawlers and
some social scrapers see no publications.

This script injects an equivalent *static* <li> list between the
PUBS:START / PUBS:END markers inside that <ol>. The client-side JS still runs
on top (it wipes and re-renders the list with copy-citation buttons + emits
ScholarlyArticle JSON-LD), so behaviour for real users is unchanged — this is
pure progressive enhancement / SEO hardening.

Idempotent: re-running replaces the previously injected block.
Run from anywhere; paths resolve relative to this file.

Usage: python3 render_pubs.py
"""
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
PUBS = ROOT / "data" / "pubs.json"
JOURNALS = ROOT / "data" / "journals.json"

OWNER = "Shijie Xu"
START = "<!--PUBS:START auto-generated by data/render_pubs.py; do not edit-->"
END = "<!--PUBS:END-->"


def lang(field):
    """researchmap multilingual field -> string (prefer en)."""
    if isinstance(field, dict):
        return field.get("en") or field.get("ja") or ""
    return field or ""


def fmt(s):
    """Escape text, then restore the pKa typography (matches the JS fmt())."""
    return html.escape(s or "").replace("pKa", "p<i>K</i><sub>a</sub>")


def authors_html(people):
    out = []
    for a in people or []:
        name = a.get("name", "")
        is_owner = name.rstrip("*").strip() == OWNER
        esc = html.escape(name)
        out.append(f"<u>{esc}</u>" if is_owner else esc)
    return ", ".join(out)


def tc_badge_html(total, by_year):
    """'TC: N' badge; with a hover per-year bar chart when citations_by_year exists.

    Mirrors the tcBadge() JS in index.html so the static (SEO) render and the
    client-side render produce identical markup.
    """
    years = sorted(int(y) for y in (by_year or {}) if str(y).isdigit())
    if not years:
        return f'<span class="tc">TC: {total}</span>'
    counts = {int(y): int(c) for y, c in by_year.items() if str(y).isdigit()}
    mx = max(counts.values()) or 1
    bars, aria = [], []
    for y in range(years[0], years[-1] + 1):
        n = counts.get(y, 0)
        h = max(round(n / mx * 100), 8) if n else 0
        cnt = f'<span class="tc-cnt">{n}</span>' if n else ""
        bars.append(
            f'<span class="tc-bar" style="height:{h}%" title="{y}: {n}">'
            f'{cnt}<span class="tc-yr">’{str(y)[2:]}</span></span>'
        )
        if n:
            aria.append(f"{y}: {n}")
    aria_txt = html.escape("Citations per year — " + ", ".join(aria))
    return (
        f'<span class="tc" tabindex="0">TC: {total}'
        f'<span class="tc-pop" role="img" aria-label="{aria_txt}">'
        f'<span class="tc-pop-h">Citations per year</span>'
        f'<span class="tc-plot">{"".join(bars)}</span></span></span>'
    )


def render_li(p, journals):
    journal_name = lang(p.get("publication_name"))
    dois = (p.get("identifiers") or {}).get("doi") or []
    doi = dois[0] if dois else None
    doi_link = f"https://doi.org/{doi}" if doi else None

    authors = f"<span>{authors_html((p.get('authors') or {}).get('en'))}, </span>"
    title = f"<span> “{fmt(lang(p.get('paper_title')))}”, </span>"

    # journal (em)
    if journal_name and "biorxiv" in journal_name.lower():
        img = ('<img src="docs/biorxiv.svg" alt="bioRxiv" class="biorxiv-icon" '
               'style="height:1.2em;vertical-align:middle">')
        inner = f'<a href="{html.escape(doi_link)}">{img}</a>' if doi_link else img
    else:
        jmeta = journals.get(journal_name, {})
        jlabel = html.escape(jmeta.get("abbreviation") or journal_name or "")
        inner = f'<a href="{html.escape(doi_link)}">{jlabel}</a>' if doi_link else jlabel
    journal = f"<em>{inner}</em>"

    # meta (volume/issue/pages/in-press/year)
    vol = p.get("volume") or ""
    num = p.get("number") or ""
    vol_issue = (vol + (f"({num})" if num else "")) if vol else ""
    start_pg = p.get("starting_page") or ""
    end_pg = p.get("ending_page") or ""
    page_range = (f"{start_pg}-{end_pg}" if end_pg else start_pg) if start_pg else ""
    pages = f": {page_range}" if page_range else ""
    in_press = " <em>(in press)</em>" if p.get("in_press") else ""
    year = str(p.get("publication_date") or "")[:4]
    lead = f"{html.escape(vol_issue)}{html.escape(pages)}{in_press}".strip()
    sep = f"{lead}, " if lead else ""
    meta = f"<span> {sep}<strong>{html.escape(year)}</strong></span>"

    parts = [authors, title, journal, meta]

    # other links (press release, video, ...)
    others = p.get("others")
    if isinstance(others, dict) and others:
        links = " | ".join(
            f'<a href="{html.escape(href)}">{html.escape(label)}</a>'
            for label, href in others.items()
        )
        parts.append(f'<span style="margin-left:0.5rem">({links})</span>')

    # citation count (with hover per-year chart) / impact factor
    tc = p.get("is_referenced_by_count")
    by_year = p.get("citations_by_year") or {}
    jf = (journals.get(journal_name) or {}).get("impact factor")
    badges = []
    if isinstance(tc, int) and tc > 0:
        badges.append(tc_badge_html(tc, by_year))
    if jf:
        badges.append(f"IF: {html.escape(str(jf))}")
    if badges:
        parts.append(f'<span class="pub-badges" style="margin-left:0.5rem">({", ".join(badges)})</span>')

    return "      <li>" + "".join(parts) + "</li>"


def main():
    pubs = json.loads(PUBS.read_text(encoding="utf-8"))
    journals = {}
    if JOURNALS.exists():
        journals = json.loads(JOURNALS.read_text(encoding="utf-8"))

    items = "\n".join(render_li(p, journals) for p in pubs)
    block = f"{START}\n{items}\n      {END}"

    text = INDEX.read_text(encoding="utf-8")
    ol_re = re.compile(r'(<ol id="pub-list"[^>]*>)(.*?)(</ol>)', re.DOTALL)
    if not ol_re.search(text):
        raise SystemExit('error: <ol id="pub-list"> not found in index.html')
    new = ol_re.sub(lambda m: f"{m.group(1)}\n      {block}\n    {m.group(3)}", text)
    INDEX.write_text(new, encoding="utf-8")
    print(f"Injected {len(pubs)} publication(s) into index.html.")


if __name__ == "__main__":
    main()
